### ISSUE TITLE
Bring `ibverb-support` up to date with `master`?

### ISSUE THREAD

**Issue by jaycedowell** [ledatelescope/bifrost#226]
So much has changed.  It should also clean up the unit tests for #225 since Py2.7 support was dropped.

**Comment by jaycedowell** [comment]
https://github.com/ledatelescope/bifrost/commit/0407a3077b0e95bcdf56564bedb34342a5065f30

Maybe it will even work.  There's probably some Py2 removal-related cleanup still to do.

**Comment by jaycedowell** [comment]
After fixing some autoconf problems I've moved on to:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/docker/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/site-packages/bifrost/__init__.py", line 35, in <module>
    from bifrost import core, memory, affinity, ring, block, address, udp_socket
  File "/home/docker/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/site-packages/bifrost/core.py", line 29, in <module>
    from bifrost.libbifrost import _bf, _th
  File "/home/docker/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/site-packages/bifrost/libbifrost.py", line 39, in <module>
    import bifrost.libbifrost_typehints as _th
  File "/home/docker/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/site-packages/bifrost/libbifrost_typehints.py", line 96
    class BFreduce_enum(enum.IntEnum):
    ^
IndentationError: expected an indented block after class definition on line 94
```
This seems to come from an empty `class BFtransmit_enum(enum.IntEnum)` that is generated when the type hints for `libbifrost_generated.py` is built.
