### ISSUE TITLE
TypeError from PyCLibrary

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#55]
I'm not sure if I have mentioned this before, but sometimes I get the following error. I assume it's a race condition because its occurrence is random. It happens for maybe 1 in >100 pipeline executions, and I have only seen it some pipelines (though I haven't run all pipelines >100 times). 

This error is from unit test "test_two_sequences" on feature/multi-sequence-support. 

```python 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/bifrost/block.py", line 243, in _main
    self.main()
  File "build/bdist.linux-x86_64/egg/bifrost/block.py", line 380, in main
    self.write('out_sum')):
  File "build/bdist.linux-x86_64/egg/bifrost/block.py", line 259, in izip
    next_set = [iterator.next() for iterator in iterators]
  File "build/bdist.linux-x86_64/egg/bifrost/block.py", line 285, in read
    for ring_name, sequence in self.izip(args, sequences)]):
  File "build/bdist.linux-x86_64/egg/bifrost/block.py", line 259, in izip
    next_set = [iterator.next() for iterator in iterators]
  File "build/bdist.linux-x86_64/egg/bifrost/ring.py", line 231, in read
    with self.acquire(offset, span_size) as ispan:
  File "build/bdist.linux-x86_64/egg/bifrost/ring.py", line 225, in acquire
    return ReadSpan(self, offset, size)
  File "build/bdist.linux-x86_64/egg/bifrost/ring.py", line 328, in __init__
    offset=offset, size=size), retarg=0)
  File "/home/mcranmer/usr/lib/python2.7/site-packages/pyclibrary-0.1.4-py2.7.egg/pyclibrary/c_library.py", line 498, in __call__
    res = self.func(*arg_list)
ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_s instance instead of LP_s
```

**Comment by MilesCranmer** [comment]
I should note that the stated occurrence of 1 in 100 has not been reproduced in other build systems, such as travis-ci, as in I have never seen this issue outside of my own machine (or inside a docker container on my own machine). 
My guess is therefore that this issue is due to something about my build system.

**Comment by MilesCranmer** [comment]
Closing this issue until I am able to reproduce it in another build environment.
