### ISSUE TITLE
complex ring output data != input data

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#64]
It looksl like there could be something up with complex-valued ring buffers. This code fails:

```python
#!/usr/bin/env python

import numpy as np
import os
import sys
from copy import deepcopy

import time

import bifrost.pipeline as bfp

# Test vector: real values are even, odd values are imag
TEST_VEC = np.arange(64*524288*2*2, dtype='float32').view('complex64')
TEST_VEC = TEST_VEC.reshape(64, 524288, 2) 
  
class FakeReader(object): 
    def __init__(self, filename):
        super(FakeReader, self).__init__()
        self.count = 0
    
    def read(self):
        self.count += 1

        if self.count <= 2:
            d = TEST_VEC
            return np.expand_dims(d, axis=0)
        else:
            return np.array([])
        
    def __enter__(self):
        return self
    
    def close(self):
        #self.guppi.close()
        pass
    
    def __exit__(self, type, value, tb):
        self.close()


class ReadBlock(bfp.SourceBlock):
    def __init__(self, sourcenames, gulp_nframe, *args, **kwargs):
        super(ReadBlock, self).__init__(sourcenames, gulp_nframe, *args, **kwargs)
        self.space = 'auto'
        
    def create_reader(self, sourcename):
        return FakeReader(sourcename)
         
    def on_sequence(self, ireader, sourcename):        
        ohdr = {'name': sourcename,
                'time_tag' : 1,
                '_tensor': {
                        'dtype':  'cf32',
                        'shape':  [-1, 64, 524288, 2],
                        }, 
                }
        return [ohdr]
    
    def on_data(self, reader, ospans):
        ospan  = ospans[0]
        indata = reader.read()
        nframe = indata.shape[0]
        #print ospan.data.shape, indata.shape, nframe
        if ospan.data[:nframe].shape == indata.shape:
            ospan.data[:nframe] = indata
        return [nframe]

class WriteBlock(bfp.TransformBlock):
    def __init__(self, iring, space, *args, **kwargs):
        super(WriteBlock, self).__init__([iring], *args, **kwargs)
        
    def on_sequence(self, iseqs):
        ohdr = deepcopy(iseqs[0].header)
        return [ohdr], [None]
 
    def on_data(self, ispans, ospans):
        data = ispans[0].data[0]
        
        assert np.allclose(ispans[0].data[0].real, TEST_VEC.real)
        assert np.allclose(ispans[0].data[0].imag, TEST_VEC.imag)
        return [1]


if __name__ == "__main__":
    
    filenames   = ['']
    b_read      = ReadBlock(filenames, 1, core=0)
    b_write     = WriteBlock(b_read.orings[0], space='system', core=1)
    
    pipeline = bfp.get_default_pipeline()
    pipeline.run() 
    print "All done"
```

with the following:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/bifrost/pipeline.py", line 217, in run
    self.main(active_orings)
  File "build/bdist.linux-x86_64/egg/bifrost/pipeline.py", line 345, in main
    ostrides = self.on_data(ispans, ospans)
  File "./bf_test.py", line 80, in on_data
    assert np.allclose(ispans[0].data[0].imag, TEST_VEC.imag)
AssertionError
```

Only the complex part fails the assertion test. Any ideas?

**Comment by telegraphic** [comment]
Update: this assertion comes back True:
```python
assert np.allclose(ispans[0].data[0].real[1:], ispans[0].data[0].imag[:-1])
```
so it looks like the imaginary values are an offset copy of the real values

**Comment by MilesCranmer** [comment]
There are a [few different tests](https://github.com/ledatelescope/bifrost/blob/master/test/test_block.py#L466) involving complex data in `test_block.py`, so I think this is a front end problem rather than ring buffer-level. 
I'll take a look.

**Comment by telegraphic** [comment]
Here's a slightly shorter version which points to line 60 being the problem

```python
#!/usr/bin/env python
import numpy as np
import time

import bifrost.pipeline as bfp
from bifrost.ndarray import ndarray

# Test vector: real values are even, odd values are imag
dim_x, dim_y, dim_z = 100, 100, 100
TEST_VEC = np.arange(dim_x * dim_y * dim_z *2, dtype='float32').view('complex64')
#TEST_VEC = TEST_VEC.reshape(dim_x, dim_y, dim_z) 
  
class FakeReader(object): 
    def __init__(self, filename):
        super(FakeReader, self).__init__()
        self.count = 0
    
    def read(self):
        self.count += 1
        if self.count <= 2:
            d = TEST_VEC
            return np.expand_dims(d, axis=0)
        else:
            return np.array([])
        
    def __enter__(self):
        return self
    
    def close(self):
        pass
    
    def __exit__(self, type, value, tb):
        self.close()


class ReadBlock(bfp.SourceBlock):
    def __init__(self, sourcenames, gulp_nframe, *args, **kwargs):
        super(ReadBlock, self).__init__(sourcenames, gulp_nframe, *args, **kwargs)
        self.space = 'auto'
        
    def create_reader(self, sourcename):
        return FakeReader(sourcename)
         
    def on_sequence(self, ireader, sourcename):        
        ohdr = {'name': sourcename,
                'time_tag' : 1,
                '_tensor': {
                        'dtype':  'cf32',
                        'shape':  [-1, dim_x * dim_y * dim_z],
                        }, 
                }
        return [ohdr]
    
    def on_data(self, reader, ospans):
        ospan  = ospans[0]
        indata = ndarray(reader.read())
        nframe = indata.shape[0]
        #print ospan.data.shape, indata.shape, nframe
        if ospan.data[:nframe].shape == indata.shape:
            ospan.data[0] = indata 
            print "TEST_VEC:"
            print type(indata)
            print "RE", indata.real
            print "IM", indata.imag
            print "OSPAN:"
            print type(ospan.data)
            print "RE",ospan.data[0].real
            print "IM",ospan.data[0].imag
        return [nframe]

if __name__ == "__main__":
    filenames   = ['']
    b_read      = ReadBlock(filenames, 1, core=0)    
    pipeline = bfp.get_default_pipeline()
    pipeline.run() 
```

i.e. `ospan.data[0] = indata` isn't setting things correctly

**Comment by telegraphic** [comment]
A little closer to the cause: the strides are wrong because `dtype_nbytes` in the tensor dict is returning 4 for cf32 instead of 8. Hacking the tensor property of `ring2.py` fixes this:

```python	
	@property
	def tensor(self):
		if self._tensor is not None:
			return self._tensor
		header = self.header
		shape = header['_tensor']['shape']
		ringlet_shape, frame_shape = split_shape(shape)
		nringlet       = reduce(lambda x,y:x*y, ringlet_shape, 1)
		frame_nelement = reduce(lambda x,y:x*y, frame_shape,   1)
		dtype = header['_tensor']['dtype']
		_, nbit = split_name_nbit(dtype)
		assert(nbit % 8 == 0)
		frame_nbyte = frame_nelement * nbit // 8
		
		self._tensor = {}
		self._tensor['dtype']         = dtype
		self._tensor['ringlet_shape'] = ringlet_shape
		self._tensor['nringlet']      = nringlet
		self._tensor['frame_shape']   = frame_shape
		self._tensor['frame_nbyte']   = frame_nbyte
		self._tensor['dtype_nbyte']   = nbit // 8
		
                # Danny's hack here:
		if dtype.startswith('c'):
			self._tensor['dtype_nbyte']   = nbit // 8 * 2
		return self._tensor
```

buuuut now I get segfaults (quite possibly from an earlier and forgotten hack). A related question: should line `data` property of `SpanBase` return a bifrost ndarray instead of a numpy array? (lines 330ish of ring2.py).

```python
        @property
	def data(self):
		
		# TODO: This function used to be super slow due to pyclibrary calls
		#         Check whether it still is!
		
		if self._data is not None:
			return self._data
		data_ptr = self._data_ptr
		
		space = self.ring.space
		if space == 'cuda':
			data_array = GPUArray(shape=self.shape,
			                      strides=self.strides,
			                      buffer=data_ptr,
			                      dtype=string2numpy(self.dtype))
		else:
			nringlet     = self._nringlet
			stride_bytes = self._stride_bytes
			BufferType = ctypes.c_byte*(nringlet*stride_bytes)
			data_buffer_ptr = ctypes.cast(data_ptr, ctypes.POINTER(BufferType))
			data_buffer     = data_buffer_ptr.contents
			data_array = np.ndarray(shape=self.shape,
			                        strides=self.strides,
			                        buffer=data_buffer,
			                        dtype=string2numpy(self.dtype))
		return data_array
```

**Comment by telegraphic** [comment]
Update: my 'fix' actually fails on all iteration except the last one (strange):
```
Launching 2 blocks
Waiting for blocks to finish
(1, 100)
[  0. +1.j   2. +3.j   4. +5.j   6. +7.j   8. +9.j  10.+11.j  12.+13.j
  14.+15.j  16.+17.j  18.+19.j  20.+21.j  22.+23.j  24.+25.j  26.+27.j
  28.+29.j  30.+31.j  32.+33.j  34.+35.j  36.+37.j  38.+39.j  40.+41.j
  42.+43.j  44.+45.j  46.+47.j  48.+49.j  50.+51.j  52.+53.j  54.+55.j
  56.+57.j  58.+59.j  60.+61.j  62.+63.j  64.+65.j  66.+67.j  68.+69.j
  70.+71.j  72.+73.j  74.+75.j  76.+77.j  78.+79.j  80.+81.j  82.+83.j
  84.+85.j  86.+87.j  88.+89.j  90.+91.j  92.+93.j  94.+95.j  96.+97.j
  98.+99.j   0. +1.j   2. +3.j   4. +5.j   6. +7.j   8. +9.j  10.+11.j
  12.+13.j  14.+15.j  16.+17.j  18.+19.j  20.+21.j  22.+23.j  24.+25.j
  26.+27.j  28.+29.j  30.+31.j  32.+33.j  34.+35.j  36.+37.j  38.+39.j
  40.+41.j  42.+43.j  44.+45.j  46.+47.j  48.+49.j  50.+51.j  52.+53.j
  54.+55.j  56.+57.j  58.+59.j  60.+61.j  62.+63.j  64.+65.j  66.+67.j
  68.+69.j  70.+71.j  72.+73.j  74.+75.j  76.+77.j  78.+79.j  80.+81.j
  82.+83.j  84.+85.j  86.+87.j  88.+89.j  90.+91.j  92.+93.j  94.+95.j
  96.+97.j  98.+99.j]
TEST FAIL
(1, 100)
[   0.  +1.j    2.  +3.j    4.  +5.j    6.  +7.j    8.  +9.j   10. +11.j
   12. +13.j   14. +15.j   16. +17.j   18. +19.j   20. +21.j   22. +23.j
   24. +25.j   26. +27.j   28. +29.j   30. +31.j   32. +33.j   34. +35.j
   36. +37.j   38. +39.j   40. +41.j   42. +43.j   44. +45.j   46. +47.j
   48. +49.j   50. +51.j   52. +53.j   54. +55.j   56. +57.j   58. +59.j
   60. +61.j   62. +63.j   64. +65.j   66. +67.j   68. +69.j   70. +71.j
   72. +73.j   74. +75.j   76. +77.j   78. +79.j   80. +81.j   82. +83.j
   84. +85.j   86. +87.j   88. +89.j   90. +91.j   92. +93.j   94. +95.j
   96. +97.j   98. +99.j  100.+101.j  102.+103.j  104.+105.j  106.+107.j
  108.+109.j  110.+111.j  112.+113.j  114.+115.j  116.+117.j  118.+119.j
  120.+121.j  122.+123.j  124.+125.j  126.+127.j  128.+129.j  130.+131.j
  132.+133.j  134.+135.j  136.+137.j  138.+139.j  140.+141.j  142.+143.j
  144.+145.j  146.+147.j  148.+149.j  150.+151.j  152.+153.j  154.+155.j
  156.+157.j  158.+159.j  160.+161.j  162.+163.j  164.+165.j  166.+167.j
  168.+169.j  170.+171.j  172.+173.j  174.+175.j  176.+177.j  178.+179.j
  180.+181.j  182.+183.j  184.+185.j  186.+187.j  188.+189.j  190.+191.j
  192.+193.j  194.+195.j  196.+197.j  198.+199.j]
TEST PASSED
```

May I pretty please ask for this to be a high-ish priority fix? I can't really test anything else until this is sorted...

**Comment by benbarsdell** [comment]
Can you try this out with the code as of https://github.com/ledatelescope/bifrost/commit/48fd2b703ba5977e86ae50a164c895aca5cdc706. I've integrated bf.ndarray and fixed the dtype issue.

There may still be issues with segfaults in bf.ndarray, but we can work through exactly what functionality you need in the short term if that happens.

**Comment by telegraphic** [comment]
This particular issue does indeed seem to be fixed. Closing.
