### ISSUE TITLE
as_GPUArray() not working

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#67]
This code fails:

```python
import bifrost as bf
from pycuda import gpuarray
import numpy as np

try:
    import pycuda.driver as cuda
    import pycuda.autoinit
    import pycuda.gpuarray as gpuarray
except ImportError:
    raise RuntimeError("could not load pycuda. Please check your install.")

z = np.ones((1, 2, 64, 528224), dtype='complex64')
a = gpuarray.to_gpu(z)
b = bf.ndarray(a)
c = bf.GPUArray(shape=z.shape, dtype=np.complex64)
c.set(z)
d = c.as_GPUArray()

for item in (a,b,c,d):
    print type(item), item.shape, item.dtype
```
raising:

```
<type 'numpy.complex64'>
Traceback (most recent call last):
  File "gpuarrays.py", line 27, in <module>
    d = c.as_GPUArray()
  File "build/bdist.linux-x86_64/egg/bifrost/GPUArray.py", line 125, in as_GPUArray
  File "/usr/local/lib/python2.7/dist-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
Boost.Python.ArgumentError: Python argument types in
    pycuda._driver.mem_alloc(numpy.float64)
did not match C++ signature:
    mem_alloc(unsigned long)
```

**Comment by benbarsdell** [comment]
Something's not right, you should be getting:
```
Traceback (most recent call last):
  File "./danny_gpuarray_test.py", line 19, in <module>
    d = c.as_GPUArray()
AttributeError: 'GPUArray' object has no attribute 'as_GPUArray'
```
Using this instead:
```
z = np.ones((1, 2, 64, 528224), dtype='complex64')
a = gpuarray.to_gpu(z)
b = bf.ndarray(a)
c = b.as_GPUArray()

for item in (a,b,c):
    print type(item), item.shape, item.dtype
```
gives:
```
<class 'pycuda.gpuarray.GPUArray'> (1, 2, 64, 528224) complex64
<class 'bifrost.ndarray.ndarray'> (1, 2, 64, 528224) complex64
<class 'pycuda.gpuarray.GPUArray'> (1, 2, 64, 528224) complex64
```

**Comment by telegraphic** [comment]
Ok, right you are. That was post-some hacking I did. 

To sum up the problem I'm having is:
* To get the code into my pycuda kernels I need a pycuda_GPUArray
* the bf_GPUArray doesn't have a `.as_GPUArray` method or an `.as_ndarray` method
* The bf_ndarray can't be indexed into if it's in GPU space, and the `asarray` method doesn't work on bf_GPUarrays

So the data are on the GPU in a ring buffer, but I can't manage to access them. So close yet so far!

**Comment by telegraphic** [comment]
PS: I did try and add this to `ndarray`:

```python
			if isinstance(base, bf_GPUArray):
					return ndarray.__new__(cls,
					                       space='cuda',
					                       buffer=base.buffer,
					                       shape=base.shape,
					                       dtype=base.dtype,
					                       strides=base.strides,
					                       native=np.dtype(base.dtype).isnative)
```

similar to how loading a pycuda GPUArray is done, but it didn't work :(

**Comment by telegraphic** [comment]
closing this for now as mainly answered with new ndarray work
