### ISSUE TITLE
Multiple sequence crash

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#69]
This code:
```python
#!/usr/bin/env python
import numpy as np
import time

import bifrost.pipeline as bfp
from bifrost.ndarray import ndarray

# Test vector: real values are even, odd values are imag
dim_x, dim_y, dim_z = 1, 1, 100
TEST_VEC = np.arange(dim_x * dim_y * dim_z *2, dtype='float32').view('complex64')
#TEST_VEC = TEST_VEC.reshape(dim_x, dim_y, dim_z) 

# Number of iterations to run
n_iter = 2

np.set_printoptions(precision=3)

class FakeReader(object): 
    def __init__(self, filename):
        super(FakeReader, self).__init__()
        self.count = 0
        print "Opening %s" % filename
    
    def read(self):
        self.count += 1
        if self.count <= n_iter:
            d = TEST_VEC
            return np.expand_dims(d, axis=0)
        else:
            return np.array([])
        
    def __enter__(self):
        return self
    
    def close(self):
        pass
    
    def __exit__(self, type, value, tb):
        self.close()


class ReadBlock(bfp.SourceBlock):
    def __init__(self, sourcenames, gulp_nframe, *args, **kwargs):
        super(ReadBlock, self).__init__(sourcenames, gulp_nframe, *args, **kwargs)
        self.space = 'auto'
        
    def create_reader(self, sourcename):
        return FakeReader(sourcename)
         
    def on_sequence(self, ireader, sourcename):        
        ohdr = {'name': sourcename,
                'time_tag' : 1,
                '_tensor': {
                        'dtype':  'cf32',
                        'shape':  [-1, dim_x * dim_y * dim_z],
                        }, 
                }
        return [ohdr]
    
    def on_data(self, reader, ospans):
        ospan  = ospans[0]
        indata = ndarray(reader.read())
        nframe = indata.shape[0]
        #print ospan.data.shape, indata.shape, nframe
        if ospan.data[:nframe].shape == indata.shape:
            ospan.data[0] = indata 
        return [nframe]

class CheckBlock(bfp.TransformBlock):
    def __init__(self, iring, *args, **kwargs):
        super(CheckBlock, self).__init__([iring], *args, **kwargs)
        
    def on_sequence(self, iseqs):
        ohdr = iseqs[0].header
        return [ohdr], [None]
        
    def on_data(self, ispans, ospans):
        print(ispans[0].data.shape)
        print(ispans[0].data[0])
        
        try:
            assert np.allclose(ispans[0].data.real, TEST_VEC.real, rtol=0.01)
            print "TEST PASSED"
        except AssertionError:
            print "TEST FAIL"
        return [0]

if __name__ == "__main__":
    filenames   = ['One.fil','Two.fil','Three.fil']
    b_read      = ReadBlock(filenames, 1, core=0)    
    b_check     = CheckBlock(b_read.orings[0], ospace='cuda_host', core=7)
    pipeline = bfp.get_default_pipeline()
    pipeline.run() 
```

Output:
```
Launching 2 blocks
Opening One.fil
Waiting for blocks to finish
(1, 100)
[  0. +1.j   2. +3.j   4. +5.j   6. +7.j   8. +9.j  10.+11.j  12.+13.j
  14.+15.j  16.+17.j  18.+19.j  20.+21.j  22.+23.j  24.+25.j  26.+27.j
  28.+29.j  30.+31.j  32.+33.j  34.+35.j  36.+37.j  38.+39.j  40.+41.j
  42.+43.j  44.+45.j  46.+47.j  48.+49.j  50.+51.j  52.+53.j  54.+55.j
  56.+57.j  58.+59.j  60.+61.j  62.+63.j  64.+65.j  66.+67.j  68.+69.j
  70.+71.j  72.+73.j  74.+75.j  76.+77.j  78.+79.j  80.+81.j  82.+83.j
  84.+85.j  86.+87.j  88.+89.j  90.+91.j  92.+93.j  94.+95.j  96.+97.j
  98.+99.j   0. +1.j   2. +3.j   4. +5.j   6. +7.j   8. +9.j  10.+11.j
  12.+13.j  14.+15.j  16.+17.j  18.+19.j  20.+21.j  22.+23.j  24.+25.j
  26.+27.j  28.+29.j  30.+31.j  32.+33.j  34.+35.j  36.+37.j  38.+39.j
  40.+41.j  42.+43.j  44.+45.j  46.+47.j  48.+49.j  50.+51.j  52.+53.j
  54.+55.j  56.+57.j  58.+59.j  60.+61.j  62.+63.j  64.+65.j  66.+67.j
  68.+69.j  70.+71.j  72.+73.j  74.+75.j  76.+77.j  78.+79.j  80.+81.j
  82.+83.j  84.+85.j  86.+87.j  88.+89.j  90.+91.j  92.+93.j  94.+95.j
  96.+97.j  98.+99.j]Opening Two.fil

ring_impl.cpp:299 error 4: BF_STATUS_INVALID_ARGUMENT
ring.cpp:125 error 4: BF_STATUS_INVALID_ARGUMENT
TEST FAIL
(1, 100)
[   0.  +1.j    2.  +3.j    4.  +5.j    6.  +7.j    8.  +9.j   10. +11.j
   12. +13.j   14. +15.j   16. +17.j   18. +19.j   20. +21.j   22. +23.j
   24. +25.j   26. +27.j   28. +29.j   30. +31.j   32. +33.j   34. +35.j
   36. +37.j   38. +39.j   40. +41.j   42. +43.j   44. +45.j   46. +47.j
   48. +49.j   50. +51.j   52. +53.j   54. +55.j   56. +57.j   58. +59.j
   60. +61.j   62. +63.j   64. +65.j   66. +67.j   68. +69.j   70. +71.j
   72. +73.j   74. +75.j   76. +77.j   78. +79.j   80. +81.j   82. +83.j
   84. +85.j   86. +87.j   88. +89.j   90. +91.j   92. +93.j   94. +95.j
   96. +97.j   98. +99.j  100.+101.j  102.+103.j  104.+105.j  106.+107.j
  108.+109.j  110.+111.j  112.+113.j  114.+115.j  116.+117.j  118.+119.j
  120.+121.j  122.+123.j  124.+125.j  126.+127.j  128.+129.j  130.+131.j
  132.+133.j  134.+135.j  136.+137.j  138.+139.j  140.+141.j  142.+143.j
  144.+145.j  146.+147.j  148.+149.j  150.+151.j  152.+153.j  154.+155.j
  156.+157.j  158.+159.j  160.+161.j  162.+163.j  164.+165.j  166.+167.j
  168.+169.j  170.+171.j  172.+173.j  174.+175.j  176.+177.j  178.+179.j
  180.+181.j  182.+183.j  184.+185.j  186.+187.j  188.+189.j  190.+191.j
  192.+193.j  194.+195.j  196.+197.j  198.+199.j]
TEST PASSED
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/bifrost/pipeline.py", line 217, in run
    self.main(active_orings)
  File "build/bdist.linux-x86_64/egg/bifrost/pipeline.py", line 261, in main
    oseqs = self.begin_sequences(oseq_stack, orings, oheaders, igulp_nframes=[])
  File "build/bdist.linux-x86_64/egg/bifrost/pipeline.py", line 233, in begin_sequences
    for (oring,ohdr,obuf_nframe) in zip(orings,oheaders,obuf_nframes)]
  File "build/bdist.linux-x86_64/egg/bifrost/ring2.py", line 108, in begin_sequence
    buf_nframe=buf_nframe)
  File "build/bdist.linux-x86_64/egg/bifrost/ring2.py", line 202, in __init__
    offset_from_head=offset_from_head), retarg=0)
  File "build/bdist.linux-x86_64/egg/bifrost/libbifrost.py", line 130, in _get
    status, args = _check(f)
  File "build/bdist.linux-x86_64/egg/bifrost/libbifrost.py", line 126, in _check
    raise RuntimeError(status_str)
RuntimeError: BF_STATUS_INVALID_ARGUMENT
```

**Comment by benbarsdell** [comment]
This is happening because the time_tag is not changing and therefore clashes with the previous sequence. Rings require time_tag to be different for each sequence. The WAR is to set it to a counter that increments inside on_sequence.

I ran into this myself the other day. The error message is obviously rather useless (unless you fish out the listed line of code and understand what it's doing). The behaviour is also quesionable; I may need to add support for time_tag being optional (and plumb this through to the backend).

**Comment by benbarsdell** [comment]
Actually, I can add this trivially inside SourceBlock and TransformBlock, allowing you to just not specify time_tag at all.

**Comment by telegraphic** [comment]
Fixed, thanks! Ambivalent about time_tags...
