### ISSUE TITLE
undefined symbol:GOMP_parallel

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#71]
This is a new error I am seeing inside the docker for Bifrost. It popped up soon after upgrading my NVIDIA drivers, tookit, new nvidia-docker. I have not re-tested previous versions of Bifrost yet - they may still work. 

Usually I would interpret this as is listed in the [wiki](https://github.com/ledatelescope/bifrost/wiki/Common-installation-and-execution-problems), i.e., there is a problem with my nvcc. However, this nvcc is from the nvidia docker image, and I can build and run all of the [sample programs](https://github.com/NVIDIA/nvidia-docker/wiki/Testing-the-samples) with result=PASS.

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/bifrost/__init__.py", line 43, in <module>
  File "build/bdist.linux-x86_64/egg/bifrost/core.py", line 29, in <module>
  File "build/bdist.linux-x86_64/egg/bifrost/libbifrost.py", line 102, in <module>
  File "build/bdist.linux-x86_64/egg/bifrost/libbifrost.py", line 99, in _load_bifrost_lib
  File "/usr/local/lib/python2.7/dist-packages/pyclibrary-0.1.4-py2.7.egg/pyclibrary/c_library.py", line 86, in __call__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyclibrary-0.1.4-py2.7.egg/pyclibrary/c_library.py", line 180, in __init__
    self._lib_ = self._link_library(lib, convention)
  File "/usr/local/lib/python2.7/dist-packages/pyclibrary-0.1.4-py2.7.egg/pyclibrary/backends/ctypes.py", line 123, in _link_library
    return cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libbifrost.so: undefined symbol: GOMP_parallel
```

Any ideas?

**Comment by MilesCranmer** [comment]
Related to #59

**Comment by benbarsdell** [comment]
Not sure how to repro this. Can you describe exactly what you're running, and print the output of:
`nvidia-docker --version`
and from inside the container:
`g++ --version`
`nvcc --version`
`nvidia-smi`
Also, did you rebuild the container?

**Comment by MilesCranmer** [comment]
Thanks, here is my output:

```
~/D/bifrost3 master $ nvidia-docker --version                                                        ⌘ ■
Docker version 1.12.6, build 78d1802

~/D/bifrost3 master # nvidia-docker run --rm -it -v ~/Documents/workspace/:/workspace -p 8888:8888 ledatelescope/bifrost

root@1f5c89703571:/workspace# g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@1f5c89703571:/workspace# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

root@1f5c89703571:/workspace# nvidia-smi
Sat Jan 28 22:58:30 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:01:00.0      On |                  N/A |
|  0%   47C    P8    15W / 201W |    397MiB /  4033MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

This is after building with the current /master version.

**Comment by MilesCranmer** [comment]
This build problem has disappeared on my machine. Closing until I see it again.

Thanks!
Miles
